@echo off
echo Adding changes to git...
git add .
echo Committing changes...
git commit -m "perf: add sharp and restore next/image to fix 30MB payload and improve performance"
echo Pushing to remote...
git push
echo Done!
pause
