@echo off
echo Adding changes to git...
git add .
echo Committing changes...
git commit -m "style: fix hero section subtitle to Sudan Gençlik Konseyi - Türkiye"
echo Pushing to remote...
git push
echo Done!
pause
