@echo off
echo Adding changes to git...
git add .
echo Committing changes...
git commit -m "fix: revert Next.js image component back to standard img to restore broken images"
echo Pushing to remote...
git push
echo Done!
pause
